### PR TITLE
Fix ActionServer cancelCallback declaration, doc & test

### LINKED ISSUE #866: ActionServer cancelRequestHandler() missing goalHandler param
While implementing an ActionServer I noticed the CancelCallback fn declaration is missing the GoalHandle parameter.

https://github.com/RobotWebTools/rclnodejs/blob/755a7a66f0b6bbd093a1f8d8cfcdefd3f64ea5f8/types/action_server.d.ts#L87

Based on the [ROS2 C++ action api](https://docs.ros2.org/foxy/api/rclcpp_action/classrclcpp__action_1_1Server.html#a1247929a1f116711b2056a7a254cfb51)  the CancelCallback declaration should be:
```typescript
type CancelCallback<T extends TypeClass<ActionTypeClassName>> = (
    goalHandle: ServerGoalHandle<T>
  ) => Promise<CancelResponse> | CancelResponse;
```

Additionally, test-action-server.js includes 2 test cases that need small modification to reflect this change.

### PR DESCRIPTION
**Pull request by wayneparrott**
While the ActionServer implementation will pass it's CancelCallback function a ServerGoalHandler argument, this fact is not clearly documented, not illustrated in the actionserver tests and the TS CancelCallback function declaration does not include a ServerGoalHandle parameter.
 
This PR updates docs, test suite and modifies the TypeScript CancelCallback function declaration to include a required ServerGoalHandle parameter. The change breaks existing TypeScript ActionServers that implement a custom CancelCallback function with a compilation error.  

Question: To make this a non-breaking change we can make the ServerGoalHandle optional. Thoughts?

Fix #866

### CODE REVIEW

File: types/action_server.d.ts [hunk 1]
```diff
@@ -153,14 +155,14 @@ declare module 'rclnodejs' {
...
-     * The callback should take one parameter containing the cancel request and must return a
+     * The callback should take one parameter containing the cancel request ( a GoalHandle) and must return a
      * {@link CancelResponse} value.
      *
      * There can only be one cancel callback per {@link ActionServer}, therefore calling this
      * function will replace any previously registered callback.
      * @param cancelCallback - Callback function, if not provided, then unregisters any previously registered callback.
      */
-    registerCancelCallback(cancelCallback?: CancelCallback): void;
+    registerCancelCallback(cancelCallback?: CancelCallback<T>): void;
```
Comment (minggangw) [inline types/action_server.d.ts:165]: Optional param makes sense, thanks!

**Review by minggangw — APPROVED** [review]
Thanks for updating the doc & examples, LGTM!
