### PR TITLE
Fix minor benchmark compile & runtime errors due to api changes.

### LINKED ISSUE #739: benchmark code does not build on foxy
There are issues building and running the rclcpp and rclpy benchmark code on foxy. 
One issue is the Node#create_publisher() now requires a qos argument.

### PR DESCRIPTION
**Pull request by wayneparrott**
Commit Summary

CmakeList.txt
* added example_interfaces to find_package()

publisher-stress-test.cpp
* added qos argument when creating publisher
* removed std::make_shared when creating the test message to resolve
compilation error.

subscription-stress-test.cpp
* added missing ';'

publisher-stress-test.py
* added required QoS argument when creating publisher

subscription-stress-test.py
* added required QoS argument when creating subscription

Fix #739

### CODE REVIEW

File: benchmark/rclcpp/topic/publisher-stress-test.cpp [hunk 1]
```diff
@@ -68,9 +68,9 @@ int main(int argc, char* argv[]) {
       *height_dim, *width_dim, *channel_dim};
   layout->data_offset = 0;
 
-  auto msg = std::make_shared<std_msgs::msg::UInt8MultiArray>();
-  msg->layout = *layout;
-  msg->data = std::vector<uint8_t>(1024 * amount, 255);
+  auto msg = std_msgs::msg::UInt8MultiArray();
+  msg.layout = *layout;
+  msg.data = std::vector<uint8_t>(1024 * amount, 255);
```
Comment (wayneparrott) [inline benchmark/rclcpp/topic/publisher-stress-test.cpp:73]: This change worked around a compilation error that I was stuck trying to resolve directly. So I went this direction. Please advise if there is an alternative change to the original code that will resolve the compilation problem.

Comment (minggangw) [reply benchmark/rclcpp/topic/publisher-stress-test.cpp:73]: it looks good.

**Review by minggangw — APPROVED** [review]
Thanks for making the benchmark works again, lgtm!
